//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenGartenZadohin4IS24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.RegistrationVisit = new HashSet<RegistrationVisit>();
        }
    
        public int id { get; set; }
        public string NameEvent { get; set; }
        public int OrientationId { get; set; }
    
        public virtual Orientation Orientation { get; set; }
        public virtual ICollection<RegistrationVisit> RegistrationVisit { get; set; }
    }
}
