//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenGartenZadohin4IS24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.RegistrationVisit = new HashSet<RegistrationVisit>();
        }
    
        public string GroupName { get; set; }
        public int TypeId { get; set; }
        public int id { get; set; }
    
        public virtual TypeGroup TypeGroup { get; set; }
        public virtual ICollection<RegistrationVisit> RegistrationVisit { get; set; }
    }
}
