//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenGartenZadohin4IS24.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zadohin4IS24IPSITEntities : DbContext
    {
        public Zadohin4IS24IPSITEntities()
            : base("name=Zadohin4IS24IPSITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Children> Children { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<Mark> Mark { get; set; }
        public DbSet<Orientation> Orientation { get; set; }
        public DbSet<RegistrationVisit> RegistrationVisit { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypeGroup> TypeGroup { get; set; }
    }
}
