//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenGartenZadohin4IS24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orientation
    {
        public Orientation()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int id { get; set; }
        public string OrientationName { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
    }
}
