//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenGartenZadohin4IS24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeGroup
    {
        public TypeGroup()
        {
            this.Group = new HashSet<Group>();
        }
    
        public int id { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
    }
}
